# Generated by Django 4.2 on 2023-04-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocolate', '0003_rename_slug_product_url_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('молочный', 'MILK'), ('Темный', 'DARK'), ('Какао', 'KAKAO'), ('Форма для кондитеров', 'FORMS')], default='молочный', max_length=25),
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='no_image.jpg', upload_to='product_image'),
        ),
    ]
