# Generated by Django 4.2 on 2023-04-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocolate', '0004_remove_product_image_product_color_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('milk', 'Молочный шоколад'), ('dark', 'Темный шоколад'), ('Kakao', 'Какао'), ('forms', 'Формы для кондитеров'), ('ingredients', 'Ингредиенты')], default='молочный', max_length=25),
        ),
    ]
