# Generated by Django 4.2 on 2023-04-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocolate', '0005_remove_product_category_remove_product_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('milk chocolate', 'milk chocolate'), ('dark chocolate', 'dark chocolate'), ('kakao', 'kakao'), ('ingredients', 'ingredients')], default='milk chocolate', max_length=30),
        ),
    ]
