# Generated by Django 4.2 on 2023-04-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocolate', '0006_delete_category_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('dark chocolate', 'dark chocolate'), ('ingredients', 'ingredients'), ('milk chocolate', 'milk chocolate'), ('kakao', 'kakao')], default='milk chocolate', max_length=30),
        ),
    ]
