# Generated by Django 4.2 on 2023-04-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocolate', '0007_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('dark chocolate', 'dark chocolate'), ('milk chocolate', 'milk chocolate'), ('ingredients', 'ingredients'), ('kakao', 'kakao')], default='milk chocolate', max_length=30),
        ),
    ]
